sap.ui.define([], function() {
    "use strict";
  
    return {
        "SelectionResult": [
            {
                "isSelected": false,
                "No": 1,
                "Gpart": "1100000104",
                "BpName": "Marsh Limited UK",
                "TrType": "DP",
                "PostingType": "",
                "Comments": "",
                "EndorsementRef": "",
                "InsuredName": "Asia Satellite Telecommunications Company Ltd",
                "Umr": "Direct Accounting Check",
                "ExtRef": "11000001354138930",
                "ClaimRef": "",
                "IntRef": "11000001354138930-001",
                "SectionName": "1 year IO",
                "ClaimTrRef": "",
                "BookedAmount": "42339.380",
                "ClearedAmount": "20339.380",
                "Amn": "22000.000",
                "OrigCurr": "USD",
                "RoeTr": "0.00000",
                "ExpPayCurr": "USD",
                "AllocAmnSettCurr": "0.000",
                "ExpPayAmn": "22000.000",
                "DueDate": "2022-10-21T00:00:00.000Z",
                "AllocAmn": "0.000",
                "ActCurrRec": "USD",
                "DeltaDueRoe": "0.000",
                "RoeRecCurr": "1.00000",
                "ProcessId": "20231227124659",
                "Opbel": "100000174028",
                "Vtref": "00000000000009792393",
                "Vkont": "390000000034",
                "FixedRoe": "",
                "SettAmnRoeTr": "22000.000",
                "Blart": "PO",
                "RepItem": "000",
                "Item": "0000",
                "Subitem": "000",
                "BitRef": "706592692",
                "SoaCount": "000",
                "SoaReferenceFab": "",
                "SoaId": "100000174028000000000011000001354138930-001",
                "Clearable": false,
                "SoaReference": "SOAFICAUNDERS",
                "SoaLineId": "01",
                "ClearableAmount": "0.000",
                "FinanceCleared": "0.000",
                "SoaClearable": "0.000",
                "SoaComments": "VINNY",
                "Tax": "",
                "Spart": "E3",
                "Hvorg": "",
                "TaxJurisdiction": "",
                "TaxCode": "",
                "PremiumId": "4138956",
                "Instalment": "1",
                "TaxRate": "0.000",
                "TaxBase": "",
                "Landx": "",
                "Uway": "",
                "Xblnr": "",
                "InceptionDate": "2022-09-21T00:00:00.000Z",
                "ExpiryDate": "2023-09-21T00:00:00.000Z",
                "Bukrs": "",
                "LineSize": "13.000000"
            },
            {
                "__metadata": {
                    "id": "http://fioriqa-http:8000/sap/opu/odata/sap/ZCLEARINGAPPLICATIONSERVICES_SRV/ClearingOPSet(2)",
                    "uri": "http://fioriqa-http:8000/sap/opu/odata/sap/ZCLEARINGAPPLICATIONSERVICES_SRV/ClearingOPSet(2)",
                    "type": "ZCLEARINGAPPLICATIONSERVICES_SRV.ClearingOP"
                },
                "isSelected": false,
                "No": 2,
                "Gpart": "1100000104",
                "BpName": "Marsh Limited UK",
                "TrType": "Unallocated Insurance Monies",
                "PostingType": "Premium receivable",
                "Comments": "",
                "EndorsementRef": "",
                "InsuredName": "",
                "Umr": "",
                "ExtRef": "",
                "ClaimRef": "",
                "IntRef": "",
                "SectionName": "",
                "ClaimTrRef": "",
                "BookedAmount": "0.000",
                "ClearedAmount": "0.000",
                "Amn": "-352.630",
                "OrigCurr": "USD",
                "RoeTr": "0.00000",
                "ExpPayCurr": "USD",
                "AllocAmnSettCurr": "0.000",
                "ExpPayAmn": "-352.630",
                "DueDate": "2022-07-27T00:00:00.000Z",
                "AllocAmn": "0.000",
                "ActCurrRec": "USD",
                "DeltaDueRoe": "0.000",
                "RoeRecCurr": "1.00000",
                "ProcessId": "",
                "Opbel": "070000006191",
                "Vtref": "",
                "Vkont": "390000000034",
                "FixedRoe": "",
                "SettAmnRoeTr": "-352.630",
                "Blart": "YM",
                "RepItem": "000",
                "Item": "0001",
                "Subitem": "000",
                "BitRef": "",
                "SoaCount": "000",
                "SoaReferenceFab": "",
                "SoaId": "0700000061910000001000",
                "Clearable": false,
                "SoaReference": "",
                "SoaLineId": "",
                "ClearableAmount": "0.000",
                "FinanceCleared": "0.000",
                "SoaClearable": "0.000",
                "SoaComments": "",
                "Tax": "",
                "Spart": "E3",
                "Hvorg": "P210",
                "TaxJurisdiction": "",
                "TaxCode": "",
                "PremiumId": "",
                "Instalment": "",
                "TaxRate": "0.000",
                "TaxBase": "",
                "Landx": "",
                "Uway": "",
                "Xblnr": "0000003208191718",
                "InceptionDate": null,
                "ExpiryDate": null,
                "Bukrs": "DX01",
                "LineSize": "0.000000"
            },
            {
                "__metadata": {
                    "id": "http://fioriqa-http:8000/sap/opu/odata/sap/ZCLEARINGAPPLICATIONSERVICES_SRV/ClearingOPSet(3)",
                    "uri": "http://fioriqa-http:8000/sap/opu/odata/sap/ZCLEARINGAPPLICATIONSERVICES_SRV/ClearingOPSet(3)",
                    "type": "ZCLEARINGAPPLICATIONSERVICES_SRV.ClearingOP"
                },
                "isSelected": false,
                "No": 3,
                "Gpart": "1100000104",
                "BpName": "Marsh Limited UK",
                "TrType": "Unallocated Insurance Monies",
                "PostingType": "Premium receivable",
                "Comments": "",
                "EndorsementRef": "",
                "InsuredName": "",
                "Umr": "",
                "ExtRef": "",
                "ClaimRef": "",
                "IntRef": "",
                "SectionName": "",
                "ClaimTrRef": "",
                "BookedAmount": "0.000",
                "ClearedAmount": "0.000",
                "Amn": "-16366.670",
                "OrigCurr": "USD",
                "RoeTr": "0.00000",
                "ExpPayCurr": "USD",
                "AllocAmnSettCurr": "0.000",
                "ExpPayAmn": "-16366.670",
                "DueDate": "2022-07-28T00:00:00.000Z",
                "AllocAmn": "0.000",
                "ActCurrRec": "USD",
                "DeltaDueRoe": "0.000",
                "RoeRecCurr": "1.00000",
                "ProcessId": "",
                "Opbel": "070000006216",
                "Vtref": "",
                "Vkont": "390000000034",
                "FixedRoe": "",
                "SettAmnRoeTr": "-16366.670",
                "Blart": "YM",
                "RepItem": "000",
                "Item": "0001",
                "Subitem": "000",
                "BitRef": "",
                "SoaCount": "000",
                "SoaReferenceFab": "",
                "SoaId": "0700000062160000001000",
                "Clearable": false,
                "SoaReference": "",
                "SoaLineId": "",
                "ClearableAmount": "0.000",
                "FinanceCleared": "0.000",
                "SoaClearable": "0.000",
                "SoaComments": "",
                "Tax": "",
                "Spart": "E3",
                "Hvorg": "P210",
                "TaxJurisdiction": "",
                "TaxCode": "",
                "PremiumId": "",
                "Instalment": "",
                "TaxRate": "0.000",
                "TaxBase": "",
                "Landx": "",
                "Uway": "",
                "Xblnr": "0000003215332781",
                "InceptionDate": null,
                "ExpiryDate": null,
                "Bukrs": "DX01",
                "LineSize": "0.000000"
            },
            {
                "__metadata": {
                    "id": "http://fioriqa-http:8000/sap/opu/odata/sap/ZCLEARINGAPPLICATIONSERVICES_SRV/ClearingOPSet(4)",
                    "uri": "http://fioriqa-http:8000/sap/opu/odata/sap/ZCLEARINGAPPLICATIONSERVICES_SRV/ClearingOPSet(4)",
                    "type": "ZCLEARINGAPPLICATIONSERVICES_SRV.ClearingOP"
                },
                "isSelected": false,
                "No": 4,
                "Gpart": "1100000104",
                "BpName": "Marsh Limited UK",
                "TrType": "Unallocated Insurance Monies",
                "PostingType": "Premium receivable",
                "Comments": "",
                "EndorsementRef": "",
                "InsuredName": "",
                "Umr": "",
                "ExtRef": "",
                "ClaimRef": "",
                "IntRef": "",
                "SectionName": "",
                "ClaimTrRef": "",
                "BookedAmount": "0.000",
                "ClearedAmount": "0.000",
                "Amn": "-76.550",
                "OrigCurr": "USD",
                "RoeTr": "0.00000",
                "ExpPayCurr": "USD",
                "AllocAmnSettCurr": "0.000",
                "ExpPayAmn": "-76.550",
                "DueDate": "2022-08-26T00:00:00.000Z",
                "AllocAmn": "0.000",
                "ActCurrRec": "USD",
                "DeltaDueRoe": "0.000",
                "RoeRecCurr": "1.00000",
                "ProcessId": "",
                "Opbel": "070000007247",
                "Vtref": "",
                "Vkont": "390000000034",
                "FixedRoe": "",
                "SettAmnRoeTr": "-76.550",
                "Blart": "YM",
                "RepItem": "000",
                "Item": "0001",
                "Subitem": "000",
                "BitRef": "",
                "SoaCount": "000",
                "SoaReferenceFab": "",
                "SoaId": "0700000072470000001000",
                "Clearable": false,
                "SoaReference": "",
                "SoaLineId": "",
                "ClearableAmount": "0.000",
                "FinanceCleared": "0.000",
                "SoaClearable": "0.000",
                "SoaComments": "",
                "Tax": "",
                "Spart": "E3",
                "Hvorg": "P210",
                "TaxJurisdiction": "",
                "TaxCode": "",
                "PremiumId": "",
                "Instalment": "",
                "TaxRate": "0.000",
                "TaxBase": "",
                "Landx": "",
                "Uway": "",
                "Xblnr": "0000000229449660",
                "InceptionDate": null,
                "ExpiryDate": null,
                "Bukrs": "DX01",
                "LineSize": "0.000000"
            },
            {
                "__metadata": {
                    "id": "http://fioriqa-http:8000/sap/opu/odata/sap/ZCLEARINGAPPLICATIONSERVICES_SRV/ClearingOPSet(5)",
                    "uri": "http://fioriqa-http:8000/sap/opu/odata/sap/ZCLEARINGAPPLICATIONSERVICES_SRV/ClearingOPSet(5)",
                    "type": "ZCLEARINGAPPLICATIONSERVICES_SRV.ClearingOP"
                },
                "isSelected": false,
                "No": 5,
                "Gpart": "1100000104",
                "BpName": "Marsh Limited UK",
                "TrType": "Unallocated Insurance Monies",
                "PostingType": "Premium receivable",
                "Comments": "",
                "EndorsementRef": "",
                "InsuredName": "",
                "Umr": "",
                "ExtRef": "",
                "ClaimRef": "",
                "IntRef": "",
                "SectionName": "",
                "ClaimTrRef": "",
                "BookedAmount": "0.000",
                "ClearedAmount": "0.000",
                "Amn": "-104570.100",
                "OrigCurr": "USD",
                "RoeTr": "0.00000",
                "ExpPayCurr": "USD",
                "AllocAmnSettCurr": "0.000",
                "ExpPayAmn": "-104570.100",
                "DueDate": "2022-08-30T00:00:00.000Z",
                "AllocAmn": "0.000",
                "ActCurrRec": "USD",
                "DeltaDueRoe": "0.000",
                "RoeRecCurr": "1.00000",
                "ProcessId": "",
                "Opbel": "070000007447",
                "Vtref": "",
                "Vkont": "390000000034",
                "FixedRoe": "",
                "SettAmnRoeTr": "-104570.100",
                "Blart": "YM",
                "RepItem": "000",
                "Item": "0001",
                "Subitem": "000",
                "BitRef": "",
                "SoaCount": "000",
                "SoaReferenceFab": "",
                "SoaId": "0700000074470000001000",
                "Clearable": false,
                "SoaReference": "",
                "SoaLineId": "",
                "ClearableAmount": "0.000",
                "FinanceCleared": "0.000",
                "SoaClearable": "0.000",
                "SoaComments": "",
                "Tax": "",
                "Spart": "E3",
                "Hvorg": "P210",
                "TaxJurisdiction": "",
                "TaxCode": "",
                "PremiumId": "",
                "Instalment": "",
                "TaxRate": "0.000",
                "TaxBase": "",
                "Landx": "",
                "Uway": "",
                "Xblnr": "0000003145956274",
                "InceptionDate": null,
                "ExpiryDate": null,
                "Bukrs": "DX01",
                "LineSize": "0.000000"
            },
            {
                "__metadata": {
                    "id": "http://fioriqa-http:8000/sap/opu/odata/sap/ZCLEARINGAPPLICATIONSERVICES_SRV/ClearingOPSet(6)",
                    "uri": "http://fioriqa-http:8000/sap/opu/odata/sap/ZCLEARINGAPPLICATIONSERVICES_SRV/ClearingOPSet(6)",
                    "type": "ZCLEARINGAPPLICATIONSERVICES_SRV.ClearingOP"
                },
                "isSelected": false,
                "No": 6,
                "Gpart": "1100000104",
                "BpName": "Marsh Limited UK",
                "TrType": "Unallocated Insurance Monies",
                "PostingType": "Premium receivable",
                "Comments": "CT: PREMIUMS",
                "EndorsementRef": "",
                "InsuredName": "",
                "Umr": "",
                "ExtRef": "",
                "ClaimRef": "",
                "IntRef": "",
                "SectionName": "",
                "ClaimTrRef": "",
                "BookedAmount": "0.000",
                "ClearedAmount": "0.000",
                "Amn": "-92014.630",
                "OrigCurr": "USD",
                "RoeTr": "0.00000",
                "ExpPayCurr": "USD",
                "AllocAmnSettCurr": "0.000",
                "ExpPayAmn": "-92014.630",
                "DueDate": "2022-07-23T00:00:00.000Z",
                "AllocAmn": "0.000",
                "ActCurrRec": "USD",
                "DeltaDueRoe": "0.000",
                "RoeRecCurr": "1.00000",
                "ProcessId": "",
                "Opbel": "070000006098",
                "Vtref": "",
                "Vkont": "390000000034",
                "FixedRoe": "",
                "SettAmnRoeTr": "-92014.630",
                "Blart": "YM",
                "RepItem": "000",
                "Item": "0001",
                "Subitem": "000",
                "BitRef": "",
                "SoaCount": "000",
                "SoaReferenceFab": "",
                "SoaId": "0700000060980000001000",
                "Clearable": false,
                "SoaReference": "",
                "SoaLineId": "",
                "ClearableAmount": "0.000",
                "FinanceCleared": "0.000",
                "SoaClearable": "0.000",
                "SoaComments": "",
                "Tax": "",
                "Spart": "E3",
                "Hvorg": "P210",
                "TaxJurisdiction": "",
                "TaxCode": "",
                "PremiumId": "",
                "Instalment": "",
                "TaxRate": "0.000",
                "TaxBase": "",
                "Landx": "",
                "Uway": "",
                "Xblnr": "0000003153751877",
                "InceptionDate": null,
                "ExpiryDate": null,
                "Bukrs": "DX01",
                "LineSize": "0.000000"
            },
            {
                "__metadata": {
                    "id": "http://fioriqa-http:8000/sap/opu/odata/sap/ZCLEARINGAPPLICATIONSERVICES_SRV/ClearingOPSet(7)",
                    "uri": "http://fioriqa-http:8000/sap/opu/odata/sap/ZCLEARINGAPPLICATIONSERVICES_SRV/ClearingOPSet(7)",
                    "type": "ZCLEARINGAPPLICATIONSERVICES_SRV.ClearingOP"
                },
                "isSelected": false,
                "No": 7,
                "Gpart": "1100000104",
                "BpName": "Marsh Limited UK",
                "TrType": "Unallocated Insurance Monies",
                "PostingType": "Premium receivable",
                "Comments": "CT: PREMIUMS",
                "EndorsementRef": "",
                "InsuredName": "",
                "Umr": "",
                "ExtRef": "",
                "ClaimRef": "",
                "IntRef": "",
                "SectionName": "",
                "ClaimTrRef": "",
                "BookedAmount": "0.000",
                "ClearedAmount": "0.000",
                "Amn": "-21270.870",
                "OrigCurr": "USD",
                "RoeTr": "0.00000",
                "ExpPayCurr": "USD",
                "AllocAmnSettCurr": "0.000",
                "ExpPayAmn": "-21270.870",
                "DueDate": "2022-07-23T00:00:00.000Z",
                "AllocAmn": "0.000",
                "ActCurrRec": "USD",
                "DeltaDueRoe": "0.000",
                "RoeRecCurr": "1.00000",
                "ProcessId": "",
                "Opbel": "070000006104",
                "Vtref": "",
                "Vkont": "390000000034",
                "FixedRoe": "",
                "SettAmnRoeTr": "-21270.870",
                "Blart": "YM",
                "RepItem": "000",
                "Item": "0001",
                "Subitem": "000",
                "BitRef": "",
                "SoaCount": "000",
                "SoaReferenceFab": "",
                "SoaId": "0700000061040000001000",
                "Clearable": false,
                "SoaReference": "",
                "SoaLineId": "",
                "ClearableAmount": "0.000",
                "FinanceCleared": "0.000",
                "SoaClearable": "0.000",
                "SoaComments": "",
                "Tax": "",
                "Spart": "E3",
                "Hvorg": "P210",
                "TaxJurisdiction": "",
                "TaxCode": "",
                "PremiumId": "",
                "Instalment": "",
                "TaxRate": "0.000",
                "TaxBase": "",
                "Landx": "",
                "Uway": "",
                "Xblnr": "0000003157842980",
                "InceptionDate": null,
                "ExpiryDate": null,
                "Bukrs": "DX01",
                "LineSize": "0.000000"
            },
            {
                "__metadata": {
                    "id": "http://fioriqa-http:8000/sap/opu/odata/sap/ZCLEARINGAPPLICATIONSERVICES_SRV/ClearingOPSet(8)",
                    "uri": "http://fioriqa-http:8000/sap/opu/odata/sap/ZCLEARINGAPPLICATIONSERVICES_SRV/ClearingOPSet(8)",
                    "type": "ZCLEARINGAPPLICATIONSERVICES_SRV.ClearingOP"
                },
                "isSelected": false,
                "No": 8,
                "Gpart": "1100000104",
                "BpName": "Marsh Limited UK",
                "TrType": "Unallocated Insurance Monies",
                "PostingType": "Premium receivable",
                "Comments": "CT: PREMIUMS",
                "EndorsementRef": "",
                "InsuredName": "",
                "Umr": "",
                "ExtRef": "",
                "ClaimRef": "",
                "IntRef": "",
                "SectionName": "",
                "ClaimTrRef": "",
                "BookedAmount": "0.000",
                "ClearedAmount": "0.000",
                "Amn": "-10870.390",
                "OrigCurr": "USD",
                "RoeTr": "0.00000",
                "ExpPayCurr": "USD",
                "AllocAmnSettCurr": "0.000",
                "ExpPayAmn": "-10870.390",
                "DueDate": "2022-08-03T00:00:00.000Z",
                "AllocAmn": "0.000",
                "ActCurrRec": "USD",
                "DeltaDueRoe": "0.000",
                "RoeRecCurr": "1.00000",
                "ProcessId": "",
                "Opbel": "070000006571",
                "Vtref": "",
                "Vkont": "390000000034",
                "FixedRoe": "",
                "SettAmnRoeTr": "-10870.390",
                "Blart": "YM",
                "RepItem": "000",
                "Item": "0001",
                "Subitem": "000",
                "BitRef": "",
                "SoaCount": "000",
                "SoaReferenceFab": "",
                "SoaId": "0700000065710000001000",
                "Clearable": false,
                "SoaReference": "",
                "SoaLineId": "",
                "ClearableAmount": "0.000",
                "FinanceCleared": "0.000",
                "SoaClearable": "0.000",
                "SoaComments": "",
                "Tax": "",
                "Spart": "E3",
                "Hvorg": "P210",
                "TaxJurisdiction": "",
                "TaxCode": "",
                "PremiumId": "",
                "Instalment": "",
                "TaxRate": "0.000",
                "TaxBase": "",
                "Landx": "",
                "Uway": "",
                "Xblnr": "0000003201938109",
                "InceptionDate": null,
                "ExpiryDate": null,
                "Bukrs": "DX01",
                "LineSize": "0.000000"
            },
            {
                "__metadata": {
                    "id": "http://fioriqa-http:8000/sap/opu/odata/sap/ZCLEARINGAPPLICATIONSERVICES_SRV/ClearingOPSet(9)",
                    "uri": "http://fioriqa-http:8000/sap/opu/odata/sap/ZCLEARINGAPPLICATIONSERVICES_SRV/ClearingOPSet(9)",
                    "type": "ZCLEARINGAPPLICATIONSERVICES_SRV.ClearingOP"
                },
                "isSelected": false,
                "No": 9,
                "Gpart": "1100000104",
                "BpName": "Marsh Limited UK",
                "TrType": "Unallocated Insurance Monies",
                "PostingType": "Premium receivable",
                "Comments": "CT: PREMIUMS",
                "EndorsementRef": "",
                "InsuredName": "",
                "Umr": "",
                "ExtRef": "",
                "ClaimRef": "",
                "IntRef": "",
                "SectionName": "",
                "ClaimTrRef": "",
                "BookedAmount": "0.000",
                "ClearedAmount": "0.000",
                "Amn": "-8699722.790",
                "OrigCurr": "USD",
                "RoeTr": "0.00000",
                "ExpPayCurr": "USD",
                "AllocAmnSettCurr": "0.000",
                "ExpPayAmn": "-8699722.790",
                "DueDate": "2022-08-16T00:00:00.000Z",
                "AllocAmn": "0.000",
                "ActCurrRec": "USD",
                "DeltaDueRoe": "0.000",
                "RoeRecCurr": "1.00000",
                "ProcessId": "",
                "Opbel": "070000007016",
                "Vtref": "",
                "Vkont": "390000000034",
                "FixedRoe": "",
                "SettAmnRoeTr": "-8699722.790",
                "Blart": "YM",
                "RepItem": "000",
                "Item": "0001",
                "Subitem": "000",
                "BitRef": "",
                "SoaCount": "000",
                "SoaReferenceFab": "",
                "SoaId": "0700000070160000001000",
                "Clearable": false,
                "SoaReference": "",
                "SoaLineId": "",
                "ClearableAmount": "0.000",
                "FinanceCleared": "0.000",
                "SoaClearable": "0.000",
                "SoaComments": "",
                "Tax": "",
                "Spart": "E3",
                "Hvorg": "P210",
                "TaxJurisdiction": "",
                "TaxCode": "",
                "PremiumId": "",
                "Instalment": "",
                "TaxRate": "0.000",
                "TaxBase": "",
                "Landx": "",
                "Uway": "",
                "Xblnr": "0000003142566794",
                "InceptionDate": null,
                "ExpiryDate": null,
                "Bukrs": "DX01",
                "LineSize": "0.000000"
            },
            {
                "__metadata": {
                    "id": "http://fioriqa-http:8000/sap/opu/odata/sap/ZCLEARINGAPPLICATIONSERVICES_SRV/ClearingOPSet(10)",
                    "uri": "http://fioriqa-http:8000/sap/opu/odata/sap/ZCLEARINGAPPLICATIONSERVICES_SRV/ClearingOPSet(10)",
                    "type": "ZCLEARINGAPPLICATIONSERVICES_SRV.ClearingOP"
                },
                "isSelected": false,
                "No": 10,
                "Gpart": "1100000104",
                "BpName": "Marsh Limited UK",
                "TrType": "Unallocated Insurance Monies",
                "PostingType": "Premium receivable",
                "Comments": "HYLAS 2_4TH INSTALLMENT",
                "EndorsementRef": "",
                "InsuredName": "",
                "Umr": "",
                "ExtRef": "",
                "ClaimRef": "",
                "IntRef": "",
                "SectionName": "",
                "ClaimTrRef": "",
                "BookedAmount": "0.000",
                "ClearedAmount": "0.000",
                "Amn": "-779.050",
                "OrigCurr": "USD",
                "RoeTr": "0.00000",
                "ExpPayCurr": "USD",
                "AllocAmnSettCurr": "0.000",
                "ExpPayAmn": "-779.050",
                "DueDate": "2022-09-06T00:00:00.000Z",
                "AllocAmn": "0.000",
                "ActCurrRec": "USD",
                "DeltaDueRoe": "0.000",
                "RoeRecCurr": "1.00000",
                "ProcessId": "",
                "Opbel": "070000007642",
                "Vtref": "",
                "Vkont": "390000000034",
                "FixedRoe": "",
                "SettAmnRoeTr": "-779.050",
                "Blart": "YM",
                "RepItem": "000",
                "Item": "0001",
                "Subitem": "000",
                "BitRef": "",
                "SoaCount": "000",
                "SoaReferenceFab": "",
                "SoaId": "0700000076420000001000",
                "Clearable": false,
                "SoaReference": "",
                "SoaLineId": "",
                "ClearableAmount": "0.000",
                "FinanceCleared": "0.000",
                "SoaClearable": "0.000",
                "SoaComments": "",
                "Tax": "",
                "Spart": "E3",
                "Hvorg": "P210",
                "TaxJurisdiction": "",
                "TaxCode": "",
                "PremiumId": "",
                "Instalment": "",
                "TaxRate": "0.000",
                "TaxBase": "",
                "Landx": "",
                "Uway": "",
                "Xblnr": "0000003242046306",
                "InceptionDate": null,
                "ExpiryDate": null,
                "Bukrs": "DX01",
                "LineSize": "0.000000"
            },
            {
                "__metadata": {
                    "id": "http://fioriqa-http:8000/sap/opu/odata/sap/ZCLEARINGAPPLICATIONSERVICES_SRV/ClearingOPSet(12)",
                    "uri": "http://fioriqa-http:8000/sap/opu/odata/sap/ZCLEARINGAPPLICATIONSERVICES_SRV/ClearingOPSet(12)",
                    "type": "ZCLEARINGAPPLICATIONSERVICES_SRV.ClearingOP"
                },
                "isSelected": false,
                "No": 12,
                "Gpart": "1100000104",
                "BpName": "Marsh Limited UK",
                "TrType": "Unallocated Insurance Monies",
                "PostingType": "Premium receivable",
                "Comments": "ZM_PREMIUMS",
                "EndorsementRef": "",
                "InsuredName": "",
                "Umr": "",
                "ExtRef": "",
                "ClaimRef": "",
                "IntRef": "",
                "SectionName": "",
                "ClaimTrRef": "",
                "BookedAmount": "0.000",
                "ClearedAmount": "0.000",
                "Amn": "-394.790",
                "OrigCurr": "USD",
                "RoeTr": "0.00000",
                "ExpPayCurr": "USD",
                "AllocAmnSettCurr": "0.000",
                "ExpPayAmn": "-394.790",
                "DueDate": "2022-08-27T00:00:00.000Z",
                "AllocAmn": "0.000",
                "ActCurrRec": "USD",
                "DeltaDueRoe": "0.000",
                "RoeRecCurr": "1.00000",
                "ProcessId": "",
                "Opbel": "070000007309",
                "Vtref": "",
                "Vkont": "390000000034",
                "FixedRoe": "",
                "SettAmnRoeTr": "-394.790",
                "Blart": "YM",
                "RepItem": "000",
                "Item": "0001",
                "Subitem": "000",
                "BitRef": "",
                "SoaCount": "000",
                "SoaReferenceFab": "",
                "SoaId": "0700000073090000001000",
                "Clearable": false,
                "SoaReference": "",
                "SoaLineId": "",
                "ClearableAmount": "0.000",
                "FinanceCleared": "0.000",
                "SoaClearable": "0.000",
                "SoaComments": "",
                "Tax": "",
                "Spart": "E3",
                "Hvorg": "P210",
                "TaxJurisdiction": "",
                "TaxCode": "",
                "PremiumId": "",
                "Instalment": "",
                "TaxRate": "0.000",
                "TaxBase": "",
                "Landx": "",
                "Uway": "",
                "Xblnr": "0000003232635169",
                "InceptionDate": null,
                "ExpiryDate": null,
                "Bukrs": "DX01",
                "LineSize": "0.000000"
            },
            {
                "__metadata": {
                    "id": "http://fioriqa-http:8000/sap/opu/odata/sap/ZCLEARINGAPPLICATIONSERVICES_SRV/ClearingOPSet(13)",
                    "uri": "http://fioriqa-http:8000/sap/opu/odata/sap/ZCLEARINGAPPLICATIONSERVICES_SRV/ClearingOPSet(13)",
                    "type": "ZCLEARINGAPPLICATIONSERVICES_SRV.ClearingOP"
                },
                "isSelected": false,
                "No": 13,
                "Gpart": "1100000104",
                "BpName": "Marsh Limited UK",
                "TrType": "Unallocated Insurance Monies",
                "PostingType": "Premium receivable",
                "Comments": "ZM_PREMIUMS",
                "EndorsementRef": "",
                "InsuredName": "",
                "Umr": "",
                "ExtRef": "",
                "ClaimRef": "",
                "IntRef": "",
                "SectionName": "",
                "ClaimTrRef": "",
                "BookedAmount": "0.000",
                "ClearedAmount": "0.000",
                "Amn": "-1218.660",
                "OrigCurr": "USD",
                "RoeTr": "0.00000",
                "ExpPayCurr": "USD",
                "AllocAmnSettCurr": "0.000",
                "ExpPayAmn": "-1218.660",
                "DueDate": "2022-08-27T00:00:00.000Z",
                "AllocAmn": "0.000",
                "ActCurrRec": "USD",
                "DeltaDueRoe": "0.000",
                "RoeRecCurr": "1.00000",
                "ProcessId": "",
                "Opbel": "070000007322",
                "Vtref": "",
                "Vkont": "390000000034",
                "FixedRoe": "",
                "SettAmnRoeTr": "-1218.660",
                "Blart": "YM",
                "RepItem": "000",
                "Item": "0001",
                "Subitem": "000",
                "BitRef": "",
                "SoaCount": "000",
                "SoaReferenceFab": "",
                "SoaId": "0700000073220000001000",
                "Clearable": false,
                "SoaReference": "",
                "SoaLineId": "",
                "ClearableAmount": "0.000",
                "FinanceCleared": "0.000",
                "SoaClearable": "0.000",
                "SoaComments": "",
                "Tax": "",
                "Spart": "E3",
                "Hvorg": "P210",
                "TaxJurisdiction": "",
                "TaxCode": "",
                "PremiumId": "",
                "Instalment": "",
                "TaxRate": "0.000",
                "TaxBase": "",
                "Landx": "",
                "Uway": "",
                "Xblnr": "0000003209189637",
                "InceptionDate": null,
                "ExpiryDate": null,
                "Bukrs": "DX01",
                "LineSize": "0.000000"
            }
        ],
        "SelectionParameters": {
            "CompanyCode": "DX01",
            "BusinessPartners": [
                "1100000002"
            ],
            "ExternalReferenceNumbers": [
                "12"
            ],
            "SoaReferenceNumbers": [],
            "UMRNumbers": [],
            "ElescoBankAccountNumber": "4021323893163050",
            "Payment": 0,
            "BankCharge": 0,
            "Currency": "USD",
            "PostingDate": null,
            "Division": "E1"
        }

    };
  });